xz1919: updated pipeline for running full test cases

diff --git a/scripts/parserTestSemanticErr b/scripts/parserTestSemanticErr
--- a/scripts/parserTestSemanticErr
+++ b/scripts/parserTestSemanticErr
@@ -3,10 +3,19 @@
 INVALID_SEMANTIC_ERR="./src/test/examples/invalid/semanticErr"
 INVALID_PARSER_SEMANTIC_ERR_LOG="./log/parse_invalid_semantic_error.log"
 
-./grun antlr.WACC program -tree $(find $INVALID_SEMANTIC_ERR -name "*.wacc") 2> $INVALID_PARSER_SEMANTIC_ERR_LOG
-
-if grep "line [0-9]*:[0-9]*" $INVALID_PARSER_SEMANTIC_ERR_LOG > /dev/null; then
-  echo "expecting no error but found the following:"
-  cat $INVALID_PARSER_SEMANTIC_ERR_LOG
-  exit 1
-fi
+for file in $(find $INVALID_SEMANTIC_ERR -name "*.wacc")
+do
+  ./compile -p $file 2> $INVALID_PARSER_SEMANTIC_ERR_LOG
+  ret=$?
+  echo "exit status with parsing only: " $ret
+  if [ $ret -ne 0 ]; then
+    echo "status code incorrect: " $ret
+    exit 1
+  fi
+  
+  if grep "line [0-9]*:[0-9]*" $INVALID_PARSER_SEMANTIC_ERR_LOG > /dev/null; then
+    echo "expecting no error but found the following:"
+    cat $INVALID_PARSER_SEMANTIC_ERR_LOG
+    exit 1
+  fi
+done
diff --git a/scripts/parserTestValid b/scripts/parserTestValid
--- a/scripts/parserTestValid
+++ b/scripts/parserTestValid
@@ -3,10 +3,19 @@
 VALID_EXAMPLES="./src/test/examples/valid"
 VALID_PARSER_EXAMPLES_LOG="./log/parse_valid_error.log"
 
-./grun antlr.WACC program -tree $(find $VALID_EXAMPLES -name "*.wacc") 2> $VALID_PARSER_EXAMPLES_LOG
-
-if grep "line [0-9]*:[0-9]*" $VALID_PARSER_EXAMPLES_LOG > /dev/null; then
-  echo "expecting no error but found the following:"
-  cat $VALID_PARSER_EXAMPLES_LOG
-  exit 1
-fi
+for file in $(find $VALID_EXAMPLES -name "*.wacc")
+do
+  ./compile $file 2> $VALID_PARSER_EXAMPLES_LOG
+  ret=$?
+  echo "exit status: " $ret
+  if [ $ret -ne 0 ]; then
+    echo "status code incorrect: " $ret
+    exit 1
+  fi
+  
+  if grep "line [0-9]*:[0-9]*" $VALID_PARSER_EXAMPLES_LOG > /dev/null; then
+    echo "expecting no error but found the following:"
+    cat $VALID_PARSER_EXAMPLES_LOG
+    exit 1
+  fi
+done
