xz1919: continue refactoring SemanticChecker, debugging compile binarySortTree.wacc

diff --git a/scripts/semanticCheckerSemanticErr b/scripts/semanticCheckerSemanticErr
--- a/scripts/semanticCheckerSemanticErr
+++ b/scripts/semanticCheckerSemanticErr
@@ -5,9 +5,9 @@ INVALID_CHECKER_SEMANTIC_ERR_LOG="./log/checker_invalid_semantic_error.log"
 
 ./compile $(find $INVALID_SEMANTIC_ERR -name "*.wacc") 2> $INVALID_CHECKER_SEMANTIC_ERR_LOG
 
-# if grep "line [0-9]*:[0-9]*" $INVALID_CHECKER_SEMANTIC_ERR_LOG > /dev/null; then
-#   echo "incorrrect error has been generated:"
-#   cat $INVALID_CHECKER_SEMANTIC_ERR_LOG
-#   echo $file
-#   exit 1
-# fi
+if grep "line [0-9]*:[0-9]*" $INVALID_CHECKER_SEMANTIC_ERR_LOG > /dev/null; then
+  echo "incorrrect error has been generated:"
+  cat $INVALID_CHECKER_SEMANTIC_ERR_LOG
+  echo $file
+  exit 1
+fi
