xz1919: added progressive pipeline scripts

diff --git a/scripts/semanticCheckerValid b/scripts/semanticCheckerValid
--- a/scripts/semanticCheckerValid
+++ b/scripts/semanticCheckerValid
@@ -1,23 +1,43 @@
 #!/bin/sh
 
-VALID_EXAMPLES="./src/test/examples/valid"
-VALID_CHECKER_EXAMPLES_LOG="./log/checker_valid_error.log"
+VALID_EXAMPLES=("./src/test/examples/valid/advanced"
+                "./src/test/examples/valid/array"
+                "./src/test/examples/valid/basic"
+                "./src/test/examples/valid/expressions"
+                "./src/test/examples/valid/function"
+                "./src/test/examples/valid/if"
+                "./src/test/examples/valid/IO"
+                "./src/test/examples/valid/pairs"
+                "./src/test/examples/valid/runtimeErr"
+                "./src/test/examples/valid/scope"
+                "./src/test/examples/valid/sequence"
+                "./src/test/examples/valid/variables"
+                "./src/test/examples/valid/while")
 
+VALID_CHECKER_EXAMPLES_LOG="./log/checker_valid_error.log"
 > $VALID_CHECKER_EXAMPLES_LOG
 
-for file in $(find $VALID_EXAMPLES -name "*.wacc") 
-do 
-  ./compile $file 2>> $VALID_CHECKER_EXAMPLES_LOG
-  ret=$?
-  if [ $ret -ne 0 ]; then
-    echo "status code incorrect: " $ret
-    exit 1
-  fi
-  echo "exit code: " $ret
-  if grep "line [0-9]*:[0-9]*" $VALID_CHECKER_EXAMPLES_LOG > /dev/null || grep "Exception" $VALID_CHECKER_EXAMPLES_LOG > /dev/null; then
-    echo "expecting no error but found the following:"
-    cat $VALID_CHECKER_EXAMPLES_LOG
-    echo $file 
-    exit 1
-  fi
+for folder in ${VALID_EXAMPLES[@]}; do
+  for file in $(find $folder -name "*.wacc") 
+  do 
+    ./compile $file 2>> $VALID_CHECKER_EXAMPLES_LOG
+    ret=$?
+    if [ $ret -ne 0 ]; then
+      echo "status code incorrect: " $ret
+      exit 1
+    fi
+    echo "exit code: " $ret
+    if grep "line [0-9]*:[0-9]*" $VALID_CHECKER_EXAMPLES_LOG > /dev/null || grep "Exception" $VALID_CHECKER_EXAMPLES_LOG > /dev/null; then
+      echo "expecting no error but found the following:"
+      cat $VALID_CHECKER_EXAMPLES_LOG
+      echo $file 
+      exit 1
+    fi
+    (( COUNTER += 1 ))
+    echo "$COUNTER / $(($TOTAL_COUNT)) finished\n"
+  done
+
+  echo "========================================================================================"
+  echo "Test Folder" $folder "has been processed" "($COUNTER / $(($TOTAL_COUNT)))"
+  echo "========================================================================================"
 done
